### ISSUE TITLE
A game's primary tag is often not a good indicator of genre

### ISSUE THREAD

**Issue by Iteria** [250/Steam-Top-250#10]
Would it be possible to display two of the tags instead of one? Some of the tags are utterly worthless on their own. "indie" and "early access" being the two that come immediately to mind. I think if there were two tags that would be perfect.

**Comment by Bilge** [comment]
Not yet, but very soon. We currently only import one tag, but to add genre breakdowns (which are coming very soon), we need to import all the tags. At that point we could add two, but I've been reluctant to add more stuff to the table because it's pretty crowded already. If you really think it would help, though, I'll consider it once the data is in place. Thanks for the suggestion 👍

**Comment by Bilge** [comment]
The biggest problem with screen space is on mobile. Do you think it would be OK to only display two tags on desktop?

**Comment by Iteria** [comment]
I don't see why the tags can't wrap, or you have some kind or "..." that a mobile user can expand. I don't think I would limit it to desktop specifically, I would use some kind of media query so that if the use has the space because they have a massive phone or they're on a tablet, then they can see the extra tags. 

I just inspected the page and I notice that you have a literal table on the page. Any reason you're not leveraging a css grid which would be a lot more flexible?

**Comment by Bilge** [comment]
Only reason would be incompetence. I'm not very good at front-end stuff like HTML and CSS, so I just bumbled my way to where we are now with a lot of help from Google.

**Comment by Iteria** [comment]
Alright, do you take pull requests? I'm going to have some time soon and I could take a crack at making a more flexible layout. I'm not particularly familiar with the templating system that you're using, but it looks like any templating system to me. I'm also not super stellar with frontend, but I say I'd was pretty mediocre. Enough to at least transform your layout into a grid system and have someone else more skilled take over.

**Comment by Bilge** [comment]
Any PR that objectively improves on what we currently have will be accepted. Keep in mind the current design is responsive from 1920x1200 all the way down to 320x480, so any revisions will need to maintain that flexibility.

**Comment by Iteria** [comment]
Okay. I'll give it a whirl. I get until then do what you can. I guess you can close this if you aren't going to take further action on it in the further.

**Comment by Bilge** [comment]
We're now importing all the tags for every game, which has more than quadrupled the database size, but means we can start tackling this problem. However, I still don't want to add more than one genre tag per game. Instead, we could blacklist certain tags that aren't very helpful in determining genre. Examples of such tags would be *early access* (which is forced always be the tag listed first) and probably *indie* (which is the most popular tag on Steam and probably overused and too vague to convey anything meaningful).

**Comment by Bilge** [comment]
@Iteria Thanks so much for bringing this issue to my attention and sorry for the delay getting it resolved. Instead of displaying more tags I decided to improve the quality of the displayed tag by blacklisting tags that are too vague to be a useful indicator of a game's genre.

The following tags are now blacklisted to prevent them appearing as the displayed tag for games:

* Early Access
* Free to Play
* Indie
* Multiplayer
* RPGMaker
* VR

This list may change over time as we identify other problematic tags.

---
Closed via 8f41e2b48a024f3c395e0847579f1c2f5069ccd6.

**Comment by Iteria** [comment]
I think you resolved this pretty quickly. I think this is a good resolution. Thanks for looking at this.
